#Project 1

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_excel('/content/Dataset for Data Analytics.xlsx')
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [15]:
print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

Rows and Columns: (1200, 14)

Column Names:
Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

Data Types:
OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

In [16]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [17]:
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

print("Missing Values After Cleaning:")
print(df.isnull().sum())

Missing Values After Cleaning:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [18]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [19]:
print(df['Date'].head())

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
Name: Date, dtype: datetime64[ns]

In [20]:
text_columns = [
    'Product',
    'ShippingAddress',
    'PaymentMethod',
    'OrderStatus',
    'CouponCode',
    'ReferralSource'
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

print("Text formatting cleaned!")

Text formatting cleaned!

In [21]:
df['UnitPrice'] = pd.to_numeric(df['UnitPrice'])
df['TotalPrice'] = pd.to_numeric(df['TotalPrice'])
df['UnitPrice'] = df['UnitPrice'].round(2)
df['TotalPrice'] = df['TotalPrice'].round(2)

print(df[['UnitPrice', 'TotalPrice', 'Date']].head())

   UnitPrice  TotalPrice       Date
0     570.62     2853.10 2023-01-04
1     151.35      302.70 2024-08-23
2     550.68     2753.40 2024-02-27
3     273.19      273.19 2023-10-15
4     626.01     2504.04 2025-05-08

#Project 2

In [22]:
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

In [24]:
print("Quantity Mean:", df['Quantity'].mean())
print("Quantity Median:", df['Quantity'].median())
print("Quantity Count:", df['Quantity'].count())

print("\nUnit Price Mean:", df['UnitPrice'].mean())
print("Unit Price Median:", df['UnitPrice'].median())
print("Unit Price Count:", df['UnitPrice'].count())

print("\nTotal Price Mean:", df['TotalPrice'].mean())
print("Total Price Median:", df['TotalPrice'].median())
print("Total Price Count:", df['TotalPrice'].count())

Quantity Mean: 2.9458333333333333
Quantity Median: 3.0
Quantity Count: 1200

Unit Price Mean: 356.41275
Unit Price Median: 364.21
Unit Price Count: 1200

Total Price Mean: 1053.9683
Total Price Median: 823.615
Total Price Count: 1200

In [29]:
product_trend = df['Product'].value_counts()

print("Product Sales Trend:")
print(product_trend)

most_common = product_trend.idxmax()
most_common_count = product_trend.max()

print("\nMost Common Product:")
print(f"{most_common} ({most_common_count} orders)")

least_common = product_trend.idxmin()
least_common_count = product_trend.min()

print("\nLeast Common Product:")
print(f"{least_common} ({least_common_count} orders)")

Product Sales Trend:
Product
Printer    181
Tablet     179
Chair      178
Laptop     173
Desk       170
Monitor    163
Phone      156
Name: count, dtype: int64

Most Common Product:
Printer (181 orders)

Least Common Product:
Phone (156 orders)

In [27]:
Q1 = df['TotalPrice'].quantile(0.25)
Q3 = df['TotalPrice'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df['TotalPrice'] < lower_bound) |
    (df['TotalPrice'] > upper_bound)
]

print("Number of Outliers:", len(outliers))
outliers.head()

Number of Outliers: 8

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
107,ORD200107,2023-03-27,C16775,Printer,5,670.75,848 Main St,Gift Card,Shipped,TRK34392124,8,FREESHIP,Instagram,3353.75
326,ORD200326,2024-07-01,C65986,Laptop,5,670.48,273 Main St,Gift Card,Returned,TRK98353867,5,SAVE10,Facebook,3352.40
328,ORD200328,2023-02-28,C18404,Tablet,5,674.04,546 Main St,Online,Cancelled,TRK89401624,7,SAVE10,Google,3370.20
469,ORD200469,2023-11-26,C13877,Chair,5,676.98,893 Main St,Cash,Cancelled,TRK17254691,5,No Coupon,Facebook,3384.90
632,ORD200632,2023-05-02,C67260,Laptop,5,678.16,463 Main St,Gift Card,Delivered,TRK38229104,7,WINTER15,Facebook,3390.80